---
classes:
  - redis::service
  - diamond

## Diamond
diamond::graphite_host: 'monitor1'
diamond::collectors:
  CPUCollector: {}
#    options:
#      path: cpu
  DiskSpaceCollector: {}
  DiskUsageCollector: {}
  LoadAverageCollector: {}
  MemoryCollector: {}
  NetworkCollector: {}
  SockstatCollector: {}
  VMStatCollector: {}
