---
classes:
  - wirbelsturm_yumrepos::cloudera_cdh4
  - zookeeper::service
  - diamond

zookeeper::params {
  data_dir => '/dev/sdf/zookeeper'
}

## Diamond
diamond::graphite_host: 'monitor1'
diamond::collectors:
  CPUCollector: {}
#    options:
#      path: cpu
  DiskSpaceCollector: {}
  DiskUsageCollector: {}
  LoadAverageCollector: {}
  MemoryCollector: {}
  NetworkCollector: {}
  SockstatCollector: {}
  VMStatCollector: {}

# Log rotation @ 4:15am PST (12:15pm UTC)
# cron::job {
#   'zookeeper_logrotate':
#     minute      => '15',
#     hour        => '12',
#     date        => '*',
#     month       => '*',
#     weekday     => '*',
#     user        => 'root',
#     command     => '',
#     environment => [ 'MAILTO=root', 'PATH="/usr/bin:/bin"' ];
#   }